apiVersion: v1
kind: ConfigMap
metadata:
  name: reactmap-areas
data:
  areas.json: |
    {
     "type": "FeatureCollection",
     "features": [
       {
         "geometry": {
           "type": "Polygon",
           "coordinates": [
             [
               [
                 lon1,
                 lat1
               ],
               [
                 lon2,
                 lat2
               ],
               [
                 lon3,
                 lat3
               ],
               [
                 lon1,
                 lat1
               ]
             ]
           ]
         },
         "type": "Feature",
         "id": 0,
         "properties": {
           "name": "Unknown Areaname",
           "stroke-opacity": 1.0,
           "fill-opacity": 0.5,
           "stroke": "#352BFF",
           "stroke-width": 2.0,
           "fill": "#0651FF",
           "hidden": false,
           "parent": "USA"
         }
       }
     ]
    }
